<%@ Page Title="" Language="C#" MasterPageFile="~/PMS.Master" AutoEventWireup="true" CodeBehind="ManageTask.aspx.cs" Inherits="PMS.WebForm2" %>







<asp:Content ID="Content1" ContentPlaceHolderID="cp1" runat="server">
   <%-- <script src="jquery-1.11.2.min.js"></script>
<script type="text/javascript" >

    $(function ()
    {
        $("#form-control").change(function () {
            alert("adadsasdasdas");
        });

        //$('#DropDownListProject').change(function () {

        //    alert("asdadasd");

        //    var a = $(this).val();



        //    if (a == "Please_select_project") {
        //        alert("Please_select_project");

        //    }
        //});



       

    });


</script>--%>

<form id="form1" runat="server">

<nav  class="navbar-default navbar-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav" id="main-menu">
                    <li>
                        <div class="user-img-div">
                           <asp:Image ID="userimage" runat="server" class="img-circle" />

                           
                        </div>

                    </li>
                     <li>
                        <a  href="#"> <strong> <asp:Label ID="username" runat="server"></asp:Label> </strong></a>
                    </li>

                    <li>
                        <a href="DashboardTeamleader.aspx"><i class="fa fa-dashboard "></i>Dashboard</a>
                    </li>
                      <li>
                        <a href="TaskandModuleManagement.aspx"><i class="fa fa-sitemap "></i>Create Module</a>
                         
                    </li>
                    <li>
                        <a href="ManageTask.aspx" class="active-menu"><i class="fa fa-sitemap "></i>Create/Assign Task</a>
                         
                    </li>
                    <li>
                        <a href="AnalysisTeamleader.aspx"><i class="fa fa-sitemap "></i>Analysis</a>
                         
                    </li>
                    <li>
                        <a href="TaskUpdateTeamleader.aspx"><i class="fa fa-sitemap "></i>Task Updates</a>
                         
                    </li>
                    
                   
                </ul>
            </div>

        </nav>
    <div id="page-wrapper" class="page-wrapper-cls">
            <div id="page-inner">
                
                 <div class="col-md-12">
                        <h1 class="page-head-line">Create Task</h1>
                 </div>
                <div class=" col-md-3 col-sm-3" >
                <asp:DropDownList ID="DropDownList1" CssClass="form-control" runat="server"  OnSelectedIndexChanged="DropDownList1_SelectedIndexChanged" AutoPostBack="true"></asp:DropDownList>
                </div>
                <div class=" col-md-3 col-sm-3">
                <asp:DropDownList ID="DropDownList2" CssClass="form-control" runat="server"></asp:DropDownList>
                </div>
                <div class=" col-md-3 col-sm-3">
                <asp:TextBox ID="TextBox1" placeholder="Task Name"  required="true" CssClass="form-control" runat="server" ></asp:TextBox>
                </div>
                <div class=" col-md-3 col-sm-3">
                <asp:DropDownList ID="DropDownList3" CssClass="form-control" runat="server" ></asp:DropDownList>
                </div>
                <h1>
                    &nbsp
                </h1>
                <div class=" col-md-3 col-sm-3">
                <asp:Button ID="Button1" CssClass="form-control" runat="server" Text="Create" OnClick="Button1_Click_InsertTaskAndAssign" />
                </div>
                
                <div class="col-md-12">
                <h1 class="page-head-line">Delete Task</h1>
                </div>
                    

                    <div class="col-md-3 col-sm-3">
                    <asp:DropDownList ID="DropDownListProject" runat="server" CssClass="form-control" AutoPostBack="true" OnSelectedIndexChanged="DropDownListProject_SelectedIndexChanged"></asp:DropDownList>
                        </div>
                    <div class="col-md-3 col-sm-3">
                    <asp:DropDownList ID="DropDownListModules" runat="server" CssClass="form-control" AutoPostBack="true" OnSelectedIndexChanged="DropDownListModules_SelectedIndexChanged"></asp:DropDownList>
                       
                    </div>
                    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" CssClass="table table-striped table-bordered table-hover" OnRowDeleting="GridView1_RowDeleting" DataKeyNames="TaskID" AllowPaging="True"  PageSize="5" AutoGenerateDeleteButton="True" Width="50%">
                        <Columns>
                            <asp:TemplateField HeaderText="Tasks">
                                <ItemTemplate>
                                    <asp:Label ID="Label1" runat="server" Text='<%# Bind("TaskName") %>'></asp:Label>
                                    <asp:HiddenField ID="HiddenTaskID" runat="server" Value='<%# Bind("TaskID") %>'></asp:HiddenField>
                                </ItemTemplate>
                            </asp:TemplateField>
                        </Columns>
                        
                 </asp:GridView>
                    
                    
                    
                
            <!-- /. PAGE INNER  -->
        </div>
        <!-- /. PAGE WRAPPER  -->
    </div>
      </form> 
</asp:Content>
