<%@ Page Title="" Language="C#" MasterPageFile="~/PMS.Master" AutoEventWireup="true" CodeBehind="RemoveEmployee.aspx.cs" Inherits="PMS.RemoveEmployee" %>


<asp:Content ID="Content1" ContentPlaceHolderID="cp1" runat="server">
    <%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="ajaxToolkit" %>
    <form id="form1" runat="server" method="post">
    <nav  class="navbar-default navbar-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav" id="main-menu">
                    <li>
                        <div class="user-img-div">
                           <asp:Image ID="userimage" runat="server" class="img-circle" />

                           
                        </div>

                    </li>
                     <li>
                        <a  href="#"> <strong> <asp:Label ID="username" runat="server"></asp:Label> </strong></a>
                    </li>

                    <li>
                        <a  href="DashboardAdmin.aspx"><i class="fa fa-dashboard "></i>Dashboard</a>
                    </li>
                      <li>
                        <a href="ManageEmployee.aspx"><i class="fa fa-sitemap "></i>Employee List</a>
                         
                    </li>
                    <li>
                        <a href="RemoveEmployee.aspx" class="active-menu" ><i class="fa fa-sitemap "></i>Remove Employee</a>
                         
                    </li>
                    
                   
                </ul>
            </div>

        </nav>
    <div id="page-wrapper" class="page-wrapper-cls">
            <div id="page-inner">
                
                 <div class="col-md-12">
                        <h1 class="page-head-line"> search and Remove Employee</h1>
                 </div>
                <div class=" col-md-3 col-sm-3">
                    <asp:TextBox ID="Name" runat="server" OnTextChanged="TextBox1_TextChanged" CssClass="form-control" ></asp:TextBox>
                    
                </div>
                <div class=" col-md-3 col-sm-3">
                <asp:Button ID="Search" runat="server" Text="Search"     CssClass="btn btn-default" OnClick="Search_Click"/>
                </div>
                <div class="row">
                    
                   <asp:GridView id="gd1" AutoGenerateColumns="false" runat="server" CssClass="table table-striped table-bordered table-hover" AutoGenerateDeleteButton="True" DataKeyNames="eid" OnRowDeleting="gd1_RowDeleting">
                       <Columns>
                            <asp:TemplateField HeaderText="Employee Image" >
                                <ItemTemplate>
                                    <asp:Image ID="Image1" runat="server" Width="100px" ImageUrl='<%#Bind("image_url") %>'   Height="100px"/>
                                </ItemTemplate>
                            </asp:TemplateField>
                          <%-- <asp:TemplateField HeaderText="Employee ID" >
                                <ItemTemplate>
                                    <asp:HiddenField ID="hid" runat="server" Value='<%#Bind("eid") %>'></asp:HiddenField>
                                </ItemTemplate>
                            </asp:TemplateField>--%>
                            <asp:TemplateField HeaderText="Employee Name" >
                                <ItemTemplate>
                                    <asp:Label ID="Label1" runat="server" Text='<%#Bind("ename") %>' EditRowStyle-HorizontalAlign="Center" EditRowStyle-VerticalAlign="Middle" HeaderStyle-HorizontalAlign="Center" HeaderStyle-VerticalAlign="Middle">></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Gender">
                                <ItemTemplate>
                                    <asp:Label ID="Label4" runat="server" Text='<%#Bind("egender") %>'>></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Email-ID">
                                <ItemTemplate>
                                    <asp:Label ID="Label2" runat="server" Text='<%#Bind("eemail") %>'>></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Contact">
                                <ItemTemplate>
                                    <asp:Label ID="Label3" runat="server" Text='<%#Bind("econtct") %>'>></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            
                            
                            <%--<asp:TemplateField HeaderText="Designation">
                                <ItemTemplate>
                                    <asp:Label ID="Label6" runat="server" Text='<%#Bind("Role") %>'>></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>--%>
                            <%--<asp:TemplateField HeaderText="Country">
                                <ItemTemplate>
                                    <asp:Label ID="Label7" runat="server" Text='<%#Bind("CountryName") %>'>></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>--%>
                            
                            
                            
                            
                        </Columns>
                    </asp:GridView>
                </div>

                
            <!-- /. PAGE INNER  -->
        </div>
        <!-- /. PAGE WRAPPER  -->
    </div>
    </form>

</asp:Content>
