<%@ Page Title="" Language="C#" MasterPageFile="~/PMS.Master" AutoEventWireup="true" CodeBehind="TaskandModuleManagement.aspx.cs" Inherits="PMS.TaskandModuleManagement" %>
<%@ Register assembly="AjaxControlToolkit" namespace="AjaxControlToolkit" tagprefix="asp" %>
<asp:Content ID="Content1" ContentPlaceHolderID="cp1" runat="server">
    <form id="form1" runat="server">
    <nav  class="navbar-default navbar-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav" id="main-menu">
                    <li>
                        <div class="user-img-div">
                           <asp:Image ID="userimage" runat="server" class="img-circle" />

                           
                        </div>

                    </li>
                     <li>
                        <a  href="#"> <strong> <asp:Label ID="username" runat="server"></asp:Label> </strong></a>
                    </li>

                    <li>
                        <a href="DashboardTeamleader.aspx"><i class="fa fa-dashboard "></i>Dashboard</a>
                    </li>
                      <li>
                        <a href="TaskandModuleManagement.aspx" class="active-menu"><i class="fa fa-sitemap "></i>Create Module</a>
                         
                    </li>
                    <li>
                        <a href="ManageTask.aspx"><i class="fa fa-sitemap "></i>Create/Assign Task</a>
                         
                    </li>
                    <li>
                        <a href="AnalysisTeamleader.aspx"><i class="fa fa-sitemap "></i>Analysis</a>
                         
                    </li>
                    <li>
                        <a href="TaskUpdateTeamleader.aspx"><i class="fa fa-sitemap "></i>Task Updates</a>
                         
                    </li>
                    
                   
                </ul>
            </div>

        </nav>
    
        
<div id="page-wrapper" class="page-wrapper-cls">
            <div id="page-inner">
                
                 <div class="col-md-12">
                        <h1 class="page-head-line">Create modules</h1>
                 </div>
                <div class=" col-md-3 col-sm-3">
                <asp:DropDownList CssClass="form-control" ID="DropDownListproject1" runat="server">
                 </asp:DropDownList>   
                </div>

                <div class=" col-md-3 col-sm-3">
                <asp:TextBox ID="TextBox1" placeholder="Module Name" required="true" runat="server" CssClass="form-control"></asp:TextBox>
                </div>
                
                <div class=" col-md-3 col-sm-3">
                <asp:Button ID="Button1" CssClass="form-control" runat="server" Text="Create" OnClick="Button1_Click" />  
                </div>
                <div class="col-md-12">
                <h1 class="page-head-line">Delete Module</h1>
                <asp:DropDownList ID="DropDownListProject" runat="server" AutoPostBack="true" CssClass="form-control" Width="23%" OnSelectedIndexChanged="DropDownListProject_SelectedIndexChanged"></asp:DropDownList>
                    <h1>&nbsp</h1>
                    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" DataKeyNames="ModuleID" CssClass="table table-striped table-bordered table-hover" AllowPaging="True"  PageSize="5"  AutoGenerateSelectButton="false" AutoGenerateDeleteButton="true" Width="50%" OnRowDeleting="GridView1_RowDeleting">
                        <Columns>
                            <asp:TemplateField HeaderText="Modules">
                                <ItemTemplate>
                                    <asp:Label ID="Label1" runat="server" Text='<%# Bind("ModuleName") %>'></asp:Label>
                                    <asp:HiddenField ID="hd1" runat="server" Value='<%# Bind("ModuleID") %>'></asp:HiddenField>
                                </ItemTemplate>
                            </asp:TemplateField>
                        </Columns>
                        


                    </asp:GridView>
             
                    
            </div>
            <!-- /. PAGE INNER  -->
       </div>
        <!-- /. PAGE WRAPPER  -->
    </div>
            
    </form>
       


    
</asp:Content>
