<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="WebForm7.aspx.cs"  Inherits="PMS.WebForm7" %>



<html>

    <form id="form1" runat="server">
    <div>
    <asp:GridView ID="gd1" runat="server" AutoGenerateDeleteButton="true" OnRowDeleting="gd1_RowDeleting"></asp:GridView>
    </div>
    </form>

</html>


    

